stages:
  - build
  - qa
  - e2e
  - publish

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - bin/cndp-dp
    - bin/cndp

.publish-image:
  stage: publish
  before_script:
    - export AMD64_DOCKER_FILE=${CI_PROJECT_DIR}/images/amd64.dockerfile
    - export AMD64_IMAGE_NAME=${DOCKER_REGISTRY}/cno/cndp/amd64/cndp-device-plugin
    - export AMD64_DEV_IMAGE=${AMD64_IMAGE_NAME}:${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}
    - export AMD64_PROD_IMAGE=${AMD64_IMAGE_NAME}:latest
    - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD} ${DOCKER_REGISTRY}

.push-docker-image: &push-docker-image
  - docker build -t ${DOCKER_IMAGE} -f ${DOCKER_FILE} ${CI_PROJECT_DIR}
  - docker push ${DOCKER_IMAGE}

compile:
  stage: build
  script:
    - make build

test:
  stage: qa
  script:
    - make build
    - make test

static:
  stage: qa
  script:
    - make buildc
    - make static

# Publish amd64 image
#publish-image-dev-amd64:
#  extends: .publish-image
#  script:
#    - export DOCKER_FILE=${AMD64_DOCKER_FILE}
#    - export DOCKER_IMAGE=${AMD64_DEV_IMAGE}
#    - *push-docker-image
#  except:
#    - master

#publish-image-prod-amd64:
#  extends: .publish-image
#  script:
#    - export DOCKER_FILE=${AMD64_DOCKER_FILE}
#    - export DOCKER_IMAGE=${AMD64_PROD_IMAGE}
#    - *push-docker-image
#  only:
#    - master

e2e:
  stage: e2e
  script:
    - make build
    - sudo rm -f /var/log/cndp-cni-e2e.log
    - sudo rm -f /var/log/cndp-dp-e2e.log
    - cd e2e/
    - sudo -E ./e2e-test.sh --full
