# WARNING: This is an example pod spec only. Remove all comments before use.

apiVersion: v1
kind: Pod
metadata:
  name: cndp-pod                              # Pod name
  annotations:
    k8s.v1.cni.cncf.io/networks: cndp-network # List of networks to attach to this pod (i.e. network name specified in network-attachment-definition.yaml)
spec:
  containers:
  - name: cndp
    image: cndp-docker-image:latest           # Specify the docker image here
    imagePullPolicy: IfNotPresent
    command: ["tail", "-f", "/dev/null"]
    resources:
      requests:
        cndp/i40e: '1'                        # The resource requested needs to match the device plugin pool name / resource type
      limits:                                 # The number requested needs to match the amount requested in annotations list above
        cndp/i40e: '1'                        # Requests and limits should match
  restartPolicy: Never
