apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: cndp-e2e-test
  annotations:
    k8s.v1.cni.cncf.io/resourceName: cndp/e2e
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "cndp-e2e",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.1.0/24",
        "rangeStart": "192.168.1.200",
        "rangeEnd": "192.168.1.216",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "192.168.1.1"
      }
    }'
