name: AF_XDP K8s Plugins CI
on: push

jobs:
  static-analysis:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: "actions/checkout@v2"
      - name: Static Analysis
        run: make static

  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: "actions/checkout@v2"
      - name: Build
        run: make build

  unit-tests:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: "actions/checkout@v2"
      - name: Unit Tests
        run: make test

  end-to-end:
    runs-on: self-hosted
    environment: AF_XDP CI
    steps:
      - name: Checkout
        uses: "actions/checkout@v2"
      - name: Delete previous logs
        run: rm -f /var/log/afxdp-k8s-plugins/cndp-cni-e2e.log && rm -f /var/log/afxdp-k8s-plugins/cndp-dp-e2e.log
      - name: E2E Test (full host run)
        run: ulimit -l 65536 && make e2efull
      - name: E2E Test (full daemonset run)
        env:
          DOCKER_REG: ${{ secrets.DOCKER_REG }}
        run: ulimit -l 65536 && make image && cd test/e2e/ && ./e2e-test.sh --full --daemonset --ci
      - name: CNI logs
        if: always()
        run: cat /var/log/afxdp-k8s-plugins/cndp-cni-e2e.log
      - name: Device Plugin logs
        if: always()
        run: cat /var/log/afxdp-k8s-plugins/cndp-dp-e2e.log
      - name: UDS Directory
        if: always()
        run: ls -la /tmp/afxdp_dp/cndp_e2e/

