name: static-analysis

on: [push, pull_request]

jobs:
  golangci:
    name: lint
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version.
          version: latest
  hadolint:
    name: Hadolint
    runs-on: self-hosted
    steps:
        - uses: actions/checkout@v2 
        - uses: hadolint/hadolint-action@v1.5.0
          with:
               dockerfile: ./e2e/Dockerfile
  shellcheck:
    name: Shellcheck
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
  gofmt-imports:
    runs-on: self-hosted
    name: Go Import
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: go install golang.org/x/tools/cmd/goimports
      - run: test -z "$(set -o pipefail && $(go env GOPATH)/bin/goimports -l . | tee goimports.out)" || { cat goimports.out && exit 1; }
